spring:
  application:
    name: inventory-service
  datasource:
    username: postgres
    password: '1234'
    url: jdbc:postgresql://localhost:5432/inventorydb-vivactivehub
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
